### ISSUE TITLE
Oddities in FileBinarySearcher.php

### ISSUE THREAD

**Issue by shelterit** [AdamLutka/PhpWndb#1]
Having some issues with idexes and offsets trying to be read from the wrong position, and I've narrowed at least one issue down to the FileBinarySearcher.php, trying to work out the logic of readCenterBlock (...).

in logging a search, I got this, as format: $iteration, ( $from, $to ), $word ;

searchFor=[0=( 0 - 4.792.749 )] "exciting"
searchFor=[1=( 0 - 2.265.313 )] "exciting"
searchFor=[2=( 1.263.632 - 2.265.313 )] "exciting"
searchFor=[3=( 1.263.632 - 1.633.401 )] "exciting"
searchFor=[4=( 1.579.569 - 1.633.401 )] "exciting"
searchFor=[5=( 1.579.569 - 1.475.439 )] "exciting"

This 5th time throws exception "from larger than to". But even the selection of the ranges seem very odd. It's all against the same file / resource "wordnet-db/index.noun".

Any ideas?

**Comment by shelterit** [comment]
I've made a more comprehensive log;

FileBinarySearcher :: searchFor=[0=( 0 - 4.792.749 )] "exciting"
[FileBinarySearcher :: readCenterBlock]
Array
(
    [start] => 0
    [end] => 4.792.749
    [size] => 4.792.749
    [block_offset] => 2.265.302
    [block] => Array
        (
            [0] => 2265302
            [1] => 262.144
        )

)
Opened file C:\xampp\htdocs\affluxant\_lib\PhpWndb\src/../wordnet-db/index.noun
[fileReader :: readBlock]
Array
(
    [read_from_offset] => 2.265.302
    [read_block_size] => 262.144
    [filename] => C:\xampp\htdocs\affluxant\_lib\PhpWndb\src/../wordnet-db/index.noun
)
[FileBinarySearcher :: readCenterBlock]
Array
(
    [firstSep] => 10
    [lastSep] => 262119
    [blockSubstr] => 10 - 262109
)
FileBinarySearcher :: searchFor=[1=( 0 - 2.265.313 )] "exciting"
[FileBinarySearcher :: readCenterBlock]
Array
(
    [start] => 0
    [end] => 2.265.313
    [size] => 2.265.313
    [block_offset] => 1.001.584
    [block] => Array
        (
            [0] => 1001584
            [1] => 262.144
        )

)
[fileReader :: readBlock]
Array
(
    [read_from_offset] => 1.001.584
    [read_block_size] => 262.144
    [filename] => C:\xampp\htdocs\affluxant\_lib\PhpWndb\src/../wordnet-db/index.noun
)
[FileBinarySearcher :: readCenterBlock]
Array
(
    [firstSep] => 7
    [lastSep] => 262048
    [blockSubstr] => 7 - 262041
)
[Block :: findRecord]
Array
(
    [recordPrefix] => exciting
    [recordSeparator] => 

    [recordPrefixSeparator] =>  
    [start] => 
    [pattern] => 
exciting 
)
FileBinarySearcher :: searchFor=[2=( 1.263.632 - 2.265.313 )] "exciting"
[FileBinarySearcher :: readCenterBlock]
Array
(
    [start] => 1.263.632
    [end] => 2.265.313
    [size] => 1.001.681
    [block_offset] => 1.633.400
    [block] => Array
        (
            [0] => 1633400
            [1] => 262.144
        )

)
[fileReader :: readBlock]
Array
(
    [read_from_offset] => 1.633.400
    [read_block_size] => 262.144
    [filename] => C:\xampp\htdocs\affluxant\_lib\PhpWndb\src/../wordnet-db/index.noun
)
[FileBinarySearcher :: readCenterBlock]
Array
(
    [firstSep] => 0
    [lastSep] => 262132
    [blockSubstr] => 0 - 262132
)
FileBinarySearcher :: searchFor=[3=( 1.263.632 - 1.633.401 )] "exciting"
[FileBinarySearcher :: readCenterBlock]
Array
(
    [start] => 1.263.632
    [end] => 1.633.401
    [size] => 369.769
    [block_offset] => 1.317.444
    [block] => Array
        (
            [0] => 1317444
            [1] => 262.144
        )

)
[fileReader :: readBlock]
Array
(
    [read_from_offset] => 1.317.444
    [read_block_size] => 262.144
    [filename] => C:\xampp\htdocs\affluxant\_lib\PhpWndb\src/../wordnet-db/index.noun
)
[FileBinarySearcher :: readCenterBlock]
Array
(
    [firstSep] => 38
    [lastSep] => 262125
    [blockSubstr] => 38 - 262087
)
[Block :: findRecord]
Array
(
    [recordPrefix] => exciting
    [recordSeparator] => 

    [recordPrefixSeparator] =>  
    [start] => 
    [pattern] => 
exciting 
)
FileBinarySearcher :: searchFor=[4=( 1.579.569 - 1.633.401 )] "exciting"
[FileBinarySearcher :: readCenterBlock]
Array
(
    [start] => 1.579.569
    [end] => 1.633.401
    [size] => 53.832
    [block_offset] => 1.475.413
    [block] => Array
        (
            [0] => 1475413
            [1] => 262.144
        )

)
[fileReader :: readBlock]
Array
(
    [read_from_offset] => 1.475.413
    [read_block_size] => 262.144
    [filename] => C:\xampp\htdocs\affluxant\_lib\PhpWndb\src/../wordnet-db/index.noun
)
[FileBinarySearcher :: readCenterBlock]
Array
(
    [firstSep] => 25
    [lastSep] => 262142
    [blockSubstr] => 25 - 262117
)
FileBinarySearcher :: searchFor=[5=( 1.579.569 - 1.475.439 )] "exciting"

Fatal error: Uncaught InvalidArgumentException: Start offset (1579569) has to be bigger than end offset (1475439).

**Comment by shelterit** [comment]
Ok, so the logic is faulty; if you're looking for a word that's not in the first index (noun), then you get the exception, however if you previously have found a noun, and then look for your word, it seems to work. So, it must be something with the way it initialises the repositories and search them. 

I'll hunt further.

**Comment by AdamLutka** [comment]
Thank you for the information about the issue. There is the [commit](https://github.com/AdamLutka/PhpWndb/commit/f8ddfca7076ca145e1f581ba47448219ef2ad07d) in the master branche that should fix it. Let me know if it helps with your toubles please.
